const nedb = require("@seald-io/nedb");

class Recipes {
    constructor(recipesFilePath){
        console.log(recipesFilePath);
        if(recipesFilePath){
            this.recipe= new nedb(recipesFilePath);
            console.log("recipes connected to " + recipesFilePath);
            recipesFilePath;
        } else {
            this.recipe = new nedb();
        }
    }
    init() {
    this.recipe.insert({
        id: 1,
        name: "Golden Beer-Battered Fish with Chips",
        description: "Cooking cod, hake or haddock in a super-crispy batter made from sparkling water steams the fish so it's really moist",
        instructions: "<b>STEP 1</b><br/> Combine the flour, cornflour, baking powder and turmeric in a large bowl, season, then spoon 1 tbsp onto a plate and set aside. Gradually pour the beer and water into the bowl, stirring with a wooden spoon until you have a smooth, lump-free batter. Leave to rest for 30 mins while you prepare the chips. <br/><b>STEP 2</b><br/>Heat oven to 200C/fan 180C/gas 6. Boil a large pan of water, then add the chipped potatoes and boil for 2-3 mins until the outsides are just tender but not soft. drain well, then tip onto a large baking tray with the flour, oil and some salt. Gently toss together until all the potatoes are evenly coated and the flour is no longer dusty. Roast for 30 mins, turning occasionally, until the chips are golden and crisp.<b>STEP 3</b><br/> To cook the fish, heat the 1 litre oil in a deep saucepan until a drop of batter sizzles and crisps up straight away. Pat the fish dry with kitchen paper, then toss it in the reserved turmeric flour mix. Shake off any excess, then dip into the batter. Carefully lower each fillet into the hot oil and fry for 6-8 mins – depending on the thickness of the fish – until golden and crisp. Using a large slotted spoon, lift out the fish, drain on kitchen paper, then sprinkle with salt. Serve with the hot chips and Homemade tomato sauce (see 'goes well with').",
        category: "Main",
        vegetarian: false ,
        glutenFree: false,
        rating: true,
        numOfServings: 2,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Plain Flour",
                measurementSize: 80,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "CornFlour",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Baking Powder",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Tumeric",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Lager Beer",
                measurementSize: 75,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Sparking Water",
                measurementSize: 75,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "SunFlower oil",
                measurementSize: 1,
                measurementUnit: "litre",
                prepStyle: "",
                getNutrition: false,
            },
            {
                ingredientID: 7,
                ingredientName: "Haddock",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "Halved",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Desiree Potato",
                measurementSize: 750,
                measurementUnit: "g",
                prepStyle: "Peeled and Sliced into Thick Chips",
                getNutrition: true,
            },
         ] 
    });
    this.recipe.insert({
        id: 2,
        name: "Spiced carrot & lentil soup",
        description: "A delicious, spicy blend packed full of iron and low in fat to boot. It's ready in under half an hour, or can be made in a slow cooker",
        instructions: "<b>STEP 1<b><br/>Heat a large saucepan and dry-fry 2 tsp cumin seeds and a pinch of chilli flakes for 1 min, or until they start to jump around the pan and release their aromas.<br/><b>STEP 2<b><br/>Scoop out about half with a spoon and set aside. Add 2 tbsp olive oil, 600g coarsely grated carrots, 140g split red lentils, 1l hot vegetable stock and 125ml milk to the pan and bring to the boil.<br/><b>STEP 3<b/><br/>Simmer for 15 mins until the lentils have swollen and softened.<br/><b>STEP 4<b/><br/>Whizz the soup with a stick blender or in a food processor until smooth (or leave it chunky if you prefer).<br/><b>STEP 5<b/><br/>Season to taste and finish with a dollop of plain yogurt and a sprinkling of the reserved toasted spices. Serve with warmed naan breads.",
        category: "Starter",
        vegetarian: true,
        glutenFree: false,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Cumin Seeds",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Chili Flakes",
                measurementSize: 0.125,
                measurementUnit: "tsp",
                prepStyle: "(Pinch)",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Olive Oil",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Carrots",
                measurementSize: 600,
                measurementUnit: "g",
                prepStyle: "washed and coarsely grated (no need to peel)",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Split red Lentils",
                measurementSize: 140,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Vegetable Stock",
                measurementSize: 1,
                measurementUnit: "Litre",
                prepStyle: "(From a cube is fine",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Milk",
                measurementSize: 125,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 3,
        name: "Soft gingerbread",
        description: "Love gingerbread with a soft centre and crisp edges? This recipe is for you. It isn’t meant for decorations or gingerbread houses – just bake, ice and enjoy!",
        instructions: "<b>STEP 1<b/><br/>Beat the butter in a stand mixer or with electric beaters until it is soft and then beat in, one by one, the sugar, golden syrup and treacle. Beat in the egg and vanilla extract and scrape down the sides of the bowl. Tip in the flour, baking powder and ginger along with a pinch of salt and beat in the flour on a slow speed until it is just combined. The dough will be very soft at this point. Scrape the dough into a container and chill it in the fridge for about 8 hours or overnight. You don’t have to leave it for this long but it does improve the flavour.<br/><b>STEP 2<b/><br/>To roll out the dough you’ll need a non-stick work surface that is lightly dusted with flour. Scoop out a small batch of the dough (it will still be very soft) and roll it out carefully to about 2mm thick. Cut out gingerbread people or circles and transfer them to a lined baking sheet. When you have filled the sheet (leaving enough room for spreading) put it into the fridge for 30 mins along with the remaining dough (you can freeze the dough in batches, if you like).<br/><b>STEP 3<b/><br/>Heat the oven to 170C/150C fan/gas 3. Cook the gingerbread for the 10-12 minutes depending on level of crispness don’t try and remove them from the sheet until the gingerbread shapes have cooled enough. Cool completely and then decorate if you want. You can freeze the cooked gingerbread if you like, or keep for up to 3 days in an airtight container",
        category: "Snack",
        vegetarian: false ,
        glutenFree: false,
        rating: true,
        numOfServings: 20,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Butter",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "Softened",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Light Muscovado Sugar",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Golden Syrup",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Black Treacle",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Egg",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Vanilla Extract",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Plain Flour",
                measurementSize: 450,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Baking Powder",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Ground Ginger",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 4,
        name: "Sweet potato & peanut curry",
        description: "Cook this tasty, budget-friendly vegan curry for an easy family dinner. With spinach and sweet potato, it boasts two of your five-a-day and it’s under 400 calories",
        instructions: "<b>STEP 1<b/><br/>Melt 1 tbsp coconut oil in a saucepan over a medium heat and soften 1 chopped onion for 5 mins. Add 2 grated garlic cloves and a grated thumb-sized piece of ginger, and cook for 1 min until fragrant.<br/><b>STEP 2<b/><br/>Stir in 3 tbsp Thai red curry paste, 1 tbsp smooth peanut butter and 500g sweet potato, peeled and cut into chunks, then add 400ml coconut milk and 200ml water.<br/><b>STEP 3<b/><br/>Bring to the boil, turn down the heat and simmer, uncovered, for 25-30 mins or until the sweet potato is soft.</br><b>STEP 4<b/><br/>Stir through 200g spinach and the juice of 1 lime, and season well. Serve with cooked rice, and if you want some crunch, sprinkle over a few dry roasted peanuts.",
        category: "Main",
        vegetarian: true ,
        glutenFree: true,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Coconut Oil",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Onion",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Garlic Cloves",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Grated",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Ginger",
                measurementSize: 1,
                measurementUnit: "Thumb Sized",
                prepStyle: "Grated",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Thai Red Curry Paste",
                measurementSize: 3,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Smooth Peanut Butter",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Sweet Potato",
                measurementSize: 500,
                measurementUnit: "g",
                prepStyle: "Peeled and Cut into Chunks",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Coconut Milk",
                measurementSize: 400,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Spinach",
                measurementSize: 200,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Lime",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Juiced",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 5,
        name: "Easy vegetarian chilli",
        description: "Rustle up our easy vegetarian chilli. It's a great recipe for batch-cooking – you can easily double it if you have a pan big enough, and freeze the rest",
        instructions: "<b>STEP 1<b/><br/>Melt 1 tbsp coconut oil in a saucepan over a medium heat and soften 1 chopped onion for 5 mins. Add 2 grated garlic cloves and a grated thumb-sized piece of ginger, and cook for 1 min until fragrant.<br/><b>STEP 2<b/><br/>Stir in 3 tbsp Thai red curry paste, 1 tbsp smooth peanut butter and 500g sweet potato, peeled and cut into chunks, then add 400ml coconut milk and 200ml water.<br/><b>STEP 3<b/><br/>Bring to the boil, turn down the heat and simmer, uncovered, for 25-30 mins or until the sweet potato is soft.</br><b>STEP 4<b/><br/>Stir through 200g spinach and the juice of 1 lime, and season well. Serve with cooked rice, and if you want some crunch, sprinkle over a few dry roasted peanuts.",
        category: "Main",
        vegetarian: true ,
        glutenFree: false,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Vegetable Oil",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Carrot",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Celery Sticks",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Onions",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Dried Mixed Herbs",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Garlic Cloves",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Crushed or Finely Grated",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Red Pepper",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Sliced",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Green Pepper",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Sliced",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Chilli Powder",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Sweet Smoked Paprika",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 11,
                ingredientName: "Tomato Puree",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,  
            },
            {
                ingredientID: 12,
                ingredientName: "Red Kidney Beans",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 13,
                ingredientName: "Black Beans",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "drained",
                getNutrition: true,
            },
            {
                ingredientID: 14,
                ingredientName: "Canned Chopped Tomato",
                measurementSize: 800,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 15,
                ingredientName: "Vegetable Stock",
                measurementSize: 400,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
   }

   getAllEntries(){
    return new Promise((resolve, reject) => {
        this.recipe.find({}, function (err, entries) {
            if (err) {
                reject(err);
            } else {
                resolve(entries);
                console.log("function all( returns: ", entries);
            }
        });
    });
   }
}
module.exports = Recipes;