const nedb = require("@seald-io/nedb");

class Recipes {
    constructor(recipesFilePath){
        console.log(recipesFilePath);
        if(recipesFilePath){
            this.recipe= new nedb(recipesFilePath);
            console.log("recipes connected to " + recipesFilePath);
            recipesFilePath;
        } else {
            this.recipe = new nedb();
        }
    }
    init() {
    this.recipe.insert({
        id: 1,
        name: "Golden Beer-Battered Fish with Chips",
        description: "Cooking cod, hake or haddock in a super-crispy batter made from sparkling water steams the fish so it's really moist",
        instructions: "<b>STEP 1</b><br/> Combine the flour, cornflour, baking powder and turmeric in a large bowl, season, then spoon 1 tbsp onto a plate and set aside. Gradually pour the beer and water into the bowl, stirring with a wooden spoon until you have a smooth, lump-free batter. Leave to rest for 30 mins while you prepare the chips. <br/><b>STEP 2</b><br/>Heat oven to 200C/fan 180C/gas 6. Boil a large pan of water, then add the chipped potatoes and boil for 2-3 mins until the outsides are just tender but not soft. drain well, then tip onto a large baking tray with the flour, oil and some salt. Gently toss together until all the potatoes are evenly coated and the flour is no longer dusty. Roast for 30 mins, turning occasionally, until the chips are golden and crisp.<br/><b>STEP 3</b><br/> To cook the fish, heat the 1 litre oil in a deep saucepan until a drop of batter sizzles and crisps up straight away. Pat the fish dry with kitchen paper, then toss it in the reserved turmeric flour mix. Shake off any excess, then dip into the batter. Carefully lower each fillet into the hot oil and fry for 6-8 mins – depending on the thickness of the fish – until golden and crisp. Using a large slotted spoon, lift out the fish, drain on kitchen paper, then sprinkle with salt. Serve with the hot chips and Homemade tomato sauce (see 'goes well with').",
        category: "Main",
        prepTime: "15 Mins",
        cookTime: "40 Mins + 30 Mins resting",
        vegetarian: false ,
        glutenFree: false,
        rating: true,
        numOfServings: 2,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Plain Flour",
                measurementSize: 80,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "CornFlour",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Baking Powder",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Tumeric",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Lager Beer",
                measurementSize: 75,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Sparking Water",
                measurementSize: 75,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "SunFlower oil",
                measurementSize: 1,
                measurementUnit: "litre",
                prepStyle: "",
                getNutrition: false,
            },
            {
                ingredientID: 7,
                ingredientName: "Haddock",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "Halved",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Desiree Potato",
                measurementSize: 750,
                measurementUnit: "g",
                prepStyle: "Peeled and Sliced into Thick Chips",
                getNutrition: true,
            },
         ]
    });
    this.recipe.insert({
        id: 2,
        name: "Spiced carrot & lentil soup",
        description: "A delicious, spicy blend packed full of iron and low in fat to boot. It's ready in under half an hour, or can be made in a slow cooker",
        instructions: "<b>STEP 1</b> <br/>Heat a large saucepan and dry-fry 2 tsp cumin seeds and a pinch of chilli flakes for 1 min, or until they start to jump around the pan and release their aromas.<br/><b>STEP 2</b><br/>Scoop out about half with a spoon and set aside. Add 2 tbsp olive oil, 600g coarsely grated carrots, 140g split red lentils, 1l hot vegetable stock and 125ml milk to the pan and bring to the boil.<br/><b>STEP 3</b><br/>Simmer for 15 mins until the lentils have swollen and softened.<br/><b>STEP 4</b><br/>Whizz the soup with a stick blender or in a food processor until smooth (or leave it chunky if you prefer).<br/><b>STEP 5</b><br/>Season to taste and finish with a dollop of plain yogurt and a sprinkling of the reserved toasted spices. Serve with warmed naan breads.",
        category: "Starter",
        prepTime: "10 Mins",
        cookTime: "15 Mins",
        vegetarian: true,
        glutenFree: false,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Cumin Seeds",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Chili Flakes",
                measurementSize: 0.125,
                measurementUnit: "tsp",
                prepStyle: "(Pinch)",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Olive Oil",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Carrots",
                measurementSize: 600,
                measurementUnit: "g",
                prepStyle: "washed and coarsely grated (no need to peel)",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Split red Lentils",
                measurementSize: 140,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Vegetable Stock",
                measurementSize: 1,
                measurementUnit: "Litre",
                prepStyle: "(From a cube is fine",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Milk",
                measurementSize: 125,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 3,
        name: "Soft gingerbread",
        description: "Love gingerbread with a soft centre and crisp edges? This recipe is for you. It isn’t meant for decorations or gingerbread houses – just bake, ice and enjoy!",
        instructions: "<b>STEP 1</b><br/>Beat the butter in a stand mixer or with electric beaters until it is soft and then beat in, one by one, the sugar, golden syrup and treacle. Beat in the egg and vanilla extract and scrape down the sides of the bowl. Tip in the flour, baking powder and ginger along with a pinch of salt and beat in the flour on a slow speed until it is just combined. The dough will be very soft at this point. Scrape the dough into a container and chill it in the fridge for about 8 hours or overnight. You don’t have to leave it for this long but it does improve the flavour.<br/><b>STEP 2</b><br/>To roll out the dough you’ll need a non-stick work surface that is lightly dusted with flour. Scoop out a small batch of the dough (it will still be very soft) and roll it out carefully to about 2mm thick. Cut out gingerbread people or circles and transfer them to a lined baking sheet. When you have filled the sheet (leaving enough room for spreading) put it into the fridge for 30 mins along with the remaining dough (you can freeze the dough in batches, if you like).<br/><b>STEP 3</b><br/>Heat the oven to 170C/150C fan/gas 3. Cook the gingerbread for the 10-12 minutes depending on level of crispness don’t try and remove them from the sheet until the gingerbread shapes have cooled enough. Cool completely and then decorate if you want. You can freeze the cooked gingerbread if you like, or keep for up to 3 days in an airtight container",
        category: "Dessert",
        prepTime: "1 Hour",
        cookTime: "11 Mins",
        vegetarian: false ,
        glutenFree: false,
        rating: true,
        numOfServings: 20,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Butter",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "Softened",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Light Muscovado Sugar",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Golden Syrup",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Black Treacle",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Egg",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Vanilla Extract",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Plain Flour",
                measurementSize: 450,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Baking Powder",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Ground Ginger",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 4,
        name: "Sweet potato & peanut curry",
        description: "Cook this tasty, budget-friendly vegan curry for an easy family dinner. With spinach and sweet potato, it boasts two of your five-a-day and it’s under 400 calories",
        instructions: "<b>STEP 1</b><br/>Melt 1 tbsp coconut oil in a saucepan over a medium heat and soften 1 chopped onion for 5 mins. Add 2 grated garlic cloves and a grated thumb-sized piece of ginger, and cook for 1 min until fragrant.<br/><b>STEP 2</b><br/>Stir in 3 tbsp Thai red curry paste, 1 tbsp smooth peanut butter and 500g sweet potato, peeled and cut into chunks, then add 400ml coconut milk and 200ml water.<br/><b>STEP 3</b><br/>Bring to the boil, turn down the heat and simmer, uncovered, for 25-30 mins or until the sweet potato is soft.</br><b>STEP 4</b><br/>Stir through 200g spinach and the juice of 1 lime, and season well. Serve with cooked rice, and if you want some crunch, sprinkle over a few dry roasted peanuts.",
        category: "Main",
        prepTime: "15 Mins",
        cookTime: "45 Mins",
        vegetarian: true ,
        glutenFree: true,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        },
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Coconut Oil",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Onion",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Garlic Cloves",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Grated",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Ginger",
                measurementSize: 1,
                measurementUnit: "Thumb Sized",
                prepStyle: "Grated",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Thai Red Curry Paste",
                measurementSize: 3,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Smooth Peanut Butter",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Sweet Potato",
                measurementSize: 500,
                measurementUnit: "g",
                prepStyle: "Peeled and Cut into Chunks",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Coconut Milk",
                measurementSize: 400,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Spinach",
                measurementSize: 200,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Lime",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Juiced",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 5,
        name: "Easy vegetarian chilli",
        description: "Rustle up our easy vegetarian chilli. It's a great recipe for batch-cooking – you can easily double it if you have a pan big enough, and freeze the rest",
        instructions: '<b>STEP 1</b><br/>Melt 1 tbsp coconut oil in a saucepan over a medium heat and soften 1 chopped onion for 5 mins. Add 2 grated garlic cloves and a grated thumb-sized piece of ginger, and cook for 1 min until fragrant.<br/><b>STEP 2</b><br/>Stir in 3 tbsp Thai red curry paste, 1 tbsp smooth peanut butter and 500g sweet potato, peeled and cut into chunks, then add 400ml coconut milk and 200ml water.<br/><b>STEP 3</b><br/>Bring to the boil, turn down the heat and simmer, uncovered, for 25-30 mins or until the sweet potato is soft.</br><b>STEP 4</b><br/>Stir through 200g spinach and the juice of 1 lime, and season well. Serve with cooked rice, and if you want some crunch, sprinkle over a few dry roasted peanuts.',
        category: "Main",
        prepTime: "25 Mins",
        cookTime: "55 Mins",
        vegetarian: true ,
        glutenFree: false,
        rating: true,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Vegetable Oil",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Carrot",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Celery Sticks",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Onions",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Dried Mixed Herbs",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Garlic Cloves",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Crushed or Finely Grated",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Red Pepper",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Sliced",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Green Pepper",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Sliced",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Chilli Powder",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Sweet Smoked Paprika",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 11,
                ingredientName: "Tomato Puree",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,  
            },
            {
                ingredientID: 12,
                ingredientName: "Red Kidney Beans",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 13,
                ingredientName: "Black Beans",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "drained",
                getNutrition: true,
            },
            {
                ingredientID: 14,
                ingredientName: "Canned Chopped Tomato",
                measurementSize: 800,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 15,
                ingredientName: "Vegetable Stock",
                measurementSize: 400,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 6,
        name: "Hot Chocolate",
        description: "The Hairy Bikers show you how to make a creamy cup of hot chocolate, perfect for a cold winter’s day.",
        instructions: '<b>STEP 1</b><br/>Heat the vanilla pod and seeds, cinnamon stick and milk in a saucepan until boiling.<br/><b>STEP 2</b>Remove the pan from the heat and add the chocolate pieces, stirring until the chocolate melts.<br/><b>STEP 3</b><br/>Whisk the hot chocolate vigorously until frothy on top and add sugar, to taste. Serve with a dusting of nutmeg.',
        category: "Drink",
        prepTime: "Less than 30 Mins",
        cookTime: "Less than 10 Mins",
        vegetarian: true ,
        glutenFree: false,
        rating: false,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Vanilla Pod",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "split and seeds scraped out",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Cinnamon Stick",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Milk",
                measurementSize: 1,
                measurementUnit: "Litre",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Plain Chocolate",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "Chopped into Small Pieces",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Sugar",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Nutmeg",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Freshly Grated",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 7,
        name: "Slow cooker roast chicken",
        description: "Cooking a whole chicken in a slow cooker keeps it tender and moist. Serve with all the trimmings for an easy Sunday lunch.",
        instructions: '<b>STEP 1</b><br/>Scatter the onion over the base of a slow cooker. Remove any trussing string from the chicken and place, breast-side up, on top.<br/><b>STEP 2</b>Pour the oil into a small bowl. Stir in the paprika, salt and pepper. Brush the oil over the chicken.<br/><b>STEP 3</b><br/>Cover the slow cooker with the lid and cook on high for 4–4 ½ hours or until the chicken is tender and thoroughly cooked – the meat should be almost falling off the bones. Remove the lid and pierce the thickest part of the bird with a skewer and make sure the juices run clear. If you wiggle one of the legs, it should move very easily.<br/><b>STEP 4</b><br/>Transfer the chicken carefully to a board to rest.<br/><b>STEP 5</b><br/>Strain the cooking liquor through a sieve and use as a thin gravy. (You can thicken it by simmering in a saucepan or adding a couple of teaspoons of gravy granules, if you like.)<br/><b>STEP 6</b><br/>Carve into slices and serve.',
        category: "Main",
        prepTime: "Less than 30 Mins",
        cookTime: "More than 2 Hours",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Onion",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Thickly Sliced",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Whole Chicken",
                measurementSize: 1.5,
                measurementUnit: "kg",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Olive Oil",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Paprika",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Flaked Sea Salt",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Coarsely Ground Black Pepper",
                measurementSize: 0.5,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 8,
        name: "Chocolate Fridge Cake",
        description: "Sophisticated and intensely chocolatey with a hit of juicy raisins and crunchy biscuit pieces, serve this decadent chocolate fridge cake as a teatime treat.",
        instructions: '<b>STEP 1</b><br/>Put the dried fruit in a small bowl and pour in just enough brandy or juice to cover. Microwave for 2 mins until steaming, then set aside.<br/><b>STEP 2</b><br/>The non-messy way to chop chocolate is to smash it (still wrapped) onto your work surface, then unwrap it down to the foil and snap it (still in foil) into small bits using your fingers. Empty the chocolate into a microwaveable bowl. Add the butter and golden syrup, cover the bowl with cling film and microwave for 2 mins until melted. Set aside.<br/><b>STEP 3</b><br/>Meanwhile, line a 20cm square tin with baking parchment, using a little butter to stick it in place. (You can also use foil but it’s more fiddly to peel off later, or cling film if you don’t mind wrinkles on the underside of your cake.)</br><b>STEP 4</b><br/>Take a third, large bowl. Use your fingers to break the biscuits into it. Stir in the nuts, soaked fruit and soaking liquid, then mix everything together. Pour the melted chocolate into the bowl with the biscuits, using a spatula or spoon to scrape out every last bit of chocolate. Mix together until everything is coated in chocolate.<br/><b>STEP 5</b><br/>Check the ingredients list to make sure everything is accounted for (it’s surprisingly easy to miss something in this recipe), then tip the chocolate mixture into the tin, pushing well into corners and flattening the top. Put in the fridge (no need to cover) for 4 hrs or overnight until set. To serve, remove from tin, peel away the parchment and cut into 16 squares (any crumbly bits that fall off make tasty samples for the cook). Will keep for up to 1 week in an airtight container in the fridge. Can be frozen for up to 1 month.',
        category: "Dessert",
        prepTime: "20 Mins",
        cookTime: "4 Hours to Set",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 16,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Mixed Dried Fruit",
                measurementSize: 225,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Brandy",
                measurementSize: 110,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Dark Chocolate",
                measurementSize: 300,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Butter",
                measurementSize: 125,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Golden Syrup",
                measurementSize: 3,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Digestive Biscuit",
                measurementSize: 13,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Roasted Hazelnuts",
                measurementSize: 100,
                measurementUnit: "g",
                prepStyle: "Chopped",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 9,
        name: "Slow-cooker sausage casserole",
        description: "You can use your favourite type of sausages to make this family-friendly slow-cooker casserole. Serve it over pasta, in baked potatoes or with bread.",
        instructions: '<b>STEP 1</b><br/>Fry the onion and celery in the oil over a low heat until it starts to soften and cook, about 5 mins, then spoon it into the slow cooker. Fry the carrots briefly and add them too.<br/><b>STEP 2</b><br/>Brown the sausages all over in the same frying pan – make sure they get a really good colour because they won’t get any browner in the slow cooker. Transfer to the slow cooker and add the sweet potato and tomatoes.<br/><b>STEP 3</b><br/>Put the purée in the frying pan and add 250ml boiling water, swirl everything around to pick up every last bit of flavour, and tip the lot into the slow cooker. Add the herbs, stock cube and some pepper. Don’t add salt until the casserole is cooked as the stock can be quite salty. Cook on high for 4 hrs or on low for 8 hrs, then serve or leave to cool and freeze.',
        category: "Main",
        prepTime: "20 Mins",
        cookTime: "4 Hours",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Red Onion",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Celery Stick",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Finely Chopped",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Rapeseed Oil",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Carrot",
                measurementSize: 4,
                measurementUnit: "",
                prepStyle: "Cut into Fat Pieces",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Chipolatas",
                measurementSize: 12,
                measurementUnit: "",
                prepStyle: "Each Halved",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Sweet Potato",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "Peeled and Cut into Chunks",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Tin Tomatoes",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Tomato Puree",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Thyme Sprig",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Rosemary Sprig",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 11,
                ingredientName: "Beef Stock Cube",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            }
        ]
    });
    this.recipe.insert({
        id: 10,
        name: "Classic prawn cocktail",
        description: "This classic retro starter packed with juicy prawns will never go out of fashion",
        instructions: '<b>STEP 1</b><br/>Peel all but four of the prawns (reserve these for the tops). Break the lettuces into individual leaves, then divide the leaves evenly between four small glass bowls. Sprinkle the prawns over the lettuce and season with black pepper.<br/><b>STEP 2</b><br/>Mix the mayonnaise, tomato chutney, Worcestershire sauce, horseradish and Tabasco together. Season to taste with lemon juice and salt and pepper, then spoon sparingly over the prawns. Dust the top with a little paprika and sprinkle with chives. Top with the remaining prawns and serve immediately. Delicious with brown bread.',
        category: "Starter",
        prepTime: "25 Mins",
        cookTime: "No Cook",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Cooked Atlantic Shell-on Prawn",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Little Gem Lettuces",
                measurementSize: 4,
                measurementUnit: "",
                prepStyle: "Trimmed",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Mayonnaise",
                measurementSize: 5,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Tomato Chutney",
                measurementSize: 5,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Worcestershire Sauce",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Creamed Horseradish",
                measurementSize: 2,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Tabasco Sauce",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Lemon Juice",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Snipped Chive",
                measurementSize: 4,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 11,
        name: "Classic mulled wine",
        description: "Make perfectly spiced mulled wine at Christmas with our easy recipe. Use a good quality red wine like an unoaked tempranillo or try a twist with a dash of sloe gin",
        instructions: '<b>STEP 1</b><br/>Put the red wine, cinnamon, star anise, cloves, lemon zest and sugar in a large pan. Cook on a low heat for 10 mins.<br/><b>STEP 2</b><br/>Remove from the heat and cool, leaving to infuse for about 30 mins.<br/><b>STEP 3</b><br/>To serve, heat without boiling, stir in the sloe gin (if using, see tip below) and pour into mugs or heatproof glasses.',
        category: "Drink",
        prepTime: "5 Mins",
        cookTime: "15 mins",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 6,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Red Wine",
                measurementSize: 750,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Large Cinnamon Stick",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Star Anise",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Cloves",
                measurementSize: 4,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Strips Lemon Zest",
                measurementSize: 2,
                measurementUnit: "",
                prepStyle: "Pared using a vegetable",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Caster Sugar",
                measurementSize: 4,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 12,
        name: "Next level Margherita pizza",
        description: "Forget takeaways – you can’t beat a homemade Margherita pizza topped with fresh tomato sauce and melted cheese. Here's how to master this everyday classic...",
        instructions: '<b>STEP 1</b><br/>First, make the dough. Tip the flour into a bowl and add 300ml tepid water. Mix together and set aside at room temperature for 1 hr. Dissolve the yeast in 2 tbsp water and mix this and 15g of salt through the dough. Cover with cling film and leave somewhere warm to double in size for a few hours. For a sourer flavour, leave in the fridge for at least 8 hrs and up to 24 hrs – the longer you leave it the sourer it will be.<br/><b>STEP 2</b><br/>When the dough is ready, tip it onto a lightly floured surface and divide into four. Roll into balls and leave to rest, covered with a tea towel or cling film for another hour.<br/><b>STEP 3</b><br/>Now make the tomato sauce. Drain some of the juice from the can and tip the rest into a bowl with the olive oil, oregano and a generous pinch of salt, then either scrunch everything together with your fingers for a chunky sauce or blitz with a stick blender if you want it smooth. Tie the basil stalks together, bruise with the back of a knife and place in the sauce. Leave the sauce at room temperature until needed.<br/><b>STEP 4</b><br/>To make the pizza, heat a grill to its highest setting and get a heavy frying pan. On a floured surface push and stretch one of the balls of dough out into a circle roughly the same size as the frying pan. Slip the round onto a floured baking sheet and top with a quarter of the sauce, a scattering of cheese, a few basil leaves and a quarter of the mozzarella.<br/><b>STEP 5</b><br/>Get the pan very hot and carefully slide the pizza onto it. Cook for 2 mins, then put the pan under the grill for another 2 mins until the sides are puffed up and the cheese has melted. Lift onto a board, drizzle with a little olive oil if you like, then cut into wedges and serve while you make the next one.',
        category: "Main",
        prepTime: "1 hour",
        cookTime: "40 mins",
        vegetarian: false ,
        glutenFree: false,
        rating: false,
        numOfServings: 4,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Strong White Flour",
                measurementSize: 500,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Fast-Action Dried Yeast",
                measurementSize: 7,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Plum Tomatoes",
                measurementSize: 400,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Extra Virgin Olive Oil",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Dried Oregano",
                measurementSize: 0.5,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Basil",
                measurementSize: "Small Bunch",
                measurementUnit: "",
                prepStyle: "Leaves, Picked, Stalks Reserved",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Parmesan",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "Freshly Grated",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Mozzarella",
                measurementSize: 200,
                measurementUnit: "g",
                prepStyle: "From a Block, Cut into Chunks",
                getNutrition: true,
            },
        ]
    });
    this.recipe.insert({
        id: 13,
        name: "Breakfast super-shake",
        description: "This smoothie is high in natural fats and sugar - ideal if you need some fuel for intense exercise",
        instructions: '<b>STEP 1</b><br/>First, make the dough. Tip the flour into a bowl and add 300ml tepid water. Mix together and set aside at room temperature for 1 hr. Dissolve the yeast in 2 tbsp water and mix this and 15g of salt through the dough. Cover with cling film and leave somewhere warm to double in size for a few hours. For a sourer flavour, leave in the fridge for at least 8 hrs and up to 24 hrs – the longer you leave it the sourer it will be.<br/><b>STEP 2</b><br/>When the dough is ready, tip it onto a lightly floured surface and divide into four. Roll into balls and leave to rest, covered with a tea towel or cling film for another hour.<br/><b>STEP 3</b><br/>Now make the tomato sauce. Drain some of the juice from the can and tip the rest into a bowl with the olive oil, oregano and a generous pinch of salt, then either scrunch everything together with your fingers for a chunky sauce or blitz with a stick blender if you want it smooth. Tie the basil stalks together, bruise with the back of a knife and place in the sauce. Leave the sauce at room temperature until needed.<br/><b>STEP 4</b><br/>To make the pizza, heat a grill to its highest setting and get a heavy frying pan. On a floured surface push and stretch one of the balls of dough out into a circle roughly the same size as the frying pan. Slip the round onto a floured baking sheet and top with a quarter of the sauce, a scattering of cheese, a few basil leaves and a quarter of the mozzarella.<br/><b>STEP 5</b><br/>Get the pan very hot and carefully slide the pizza onto it. Cook for 2 mins, then put the pan under the grill for another 2 mins until the sides are puffed up and the cheese has melted. Lift onto a board, drizzle with a little olive oil if you like, then cut into wedges and serve while you make the next one.',
        category: "Drink",
        prepTime: "5 mins",
        cookTime: "No Cook",
        vegetarian: true,
        glutenFree: true,
        rating: false,
        numOfServings: 1,
        nutrition:{
            sugar_g: null,
            fiber_g: null,
            serving_size_g: null,
            sodium_mg: null,
            potassium_mg: null,
            fat_saturated_g: null,
            fat_total_g: null,
            calories: null,
            cholesterol_mg: null,
            protein_g: null,
            carbohydrates_total_g: null,
        }, 
        ingredientsInRecipe: [
            {
                ingredientID: 1,
                ingredientName: "Full-Fat Milk",
                measurementSize: 100,
                measurementUnit: "ml",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 2,
                ingredientName: "Natural Yogurt",
                measurementSize: 2,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 3,
                ingredientName: "Banana",
                measurementSize: 1,
                measurementUnit: "",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 4,
                ingredientName: "Frozen Fruits of the Forest",
                measurementSize: 150,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 5,
                ingredientName: "Blueberries",
                measurementSize: 50,
                measurementUnit: "g",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 6,
                ingredientName: "Chia Seeds",
                measurementSize: "1",
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 7,
                ingredientName: "Cinnamon",
                measurementSize: 0.5,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 8,
                ingredientName: "Goji Berries",
                measurementSize: 1,
                measurementUnit: "tbsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 9,
                ingredientName: "Mixed Seeds",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
            {
                ingredientID: 10,
                ingredientName: "Honey",
                measurementSize: 1,
                measurementUnit: "tsp",
                prepStyle: "",
                getNutrition: true,
            },
        ]
    });
   }

   getAllEntries(){
    return new Promise((resolve, reject) => {
        this.recipe.find({}, function (err, entries) {
            if (err) {
                reject(err);
            } else {
                resolve(entries);
                console.log("function all( returns: ", entries);
            }
        });
    });
   }

   getIngredients(){
        return new Promise((resolve, reject) => {
            this.recipe.find({}, {ingredientsInRecipe: 1}, function(err, docs) {
                if (err) {
                    reject(err);
                } else {
                    resolve(entries);
                    console.log("function all( returns: ", entries);
                }
            });
        });
   }
}
module.exports = Recipes;